version: "3.7"

services:

  accuweather-downloader:
    profiles:
      - metar
    image: weatherindex/weatherindex:sensors-${METRICS_DOCKER_VERSION}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.volume/download/metar/:/.download/metar/
    command: |
      python -m sensors
      --download-path ./download/metar
      --storage-uri ${S3_URI_METAR}
      metar

  geosphere-downloader:
    profiles:
      - geosphere
    image: weatherindex/weatherindex:sensors-${METRICS_DOCKER_VERSION}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.volume/download/geosphere/:/.download/geosphere/
    command: |
      python -m sensors
      --download-path ./download/geosphere
      --storage-uri ${S3_URI_GEOSPHERE}
      geosphere

  dwd-downloader:
    profiles:
      - dwd
    image: weatherindex/weatherindex:sensors-${METRICS_DOCKER_VERSION}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.volume/download/dwd/:/.download/dwd/
    command: |
      python -m sensors
      --download-path ./download/dwd
      --storage-uri ${S3_URI_DWD}
      dwd

  fsdiopendata-downloader:
    profiles:
      - fsdiopendata
    image: weatherindex/weatherindex:sensors-${METRICS_DOCKER_VERSION}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.volume/download/fsdiopendata/:/.download/fsdiopendata/
    command: |
      python -m sensors
      --download-path ./download/fsdiopendata
      --storage-uri ${S3_URI_FSDIOPENDATA}
      fsdiopendata
